storage_path: /workspace/FlavorGraph/Flavor_Diffusion
training_split: /workspace/FlavorGraph/Flavor_Diffusion/output_subgraphs/100/subgraphs_train.json
training_split_label_dir: null
validation_split: /workspace/FlavorGraph/Flavor_Diffusion/output_subgraphs/100/subgraphs_val.json
test_split: /workspace/FlavorGraph/Flavor_Diffusion/output_subgraphs/100/subgraphs_test.json
batch_size: 16
num_epochs: 10
learning_rate: 0.0002
weight_decay: 0.0001
lr_scheduler: cosine-decay
num_workers: 16
fp16: false
use_activation_checkpoint: false
diffusion_type: gaussian
diffusion_schedule: cosine
diffusion_steps: 1000
inference_diffusion_steps: 50
inference_schedule: cosine
inference_trick: ddim
n_layers: 12
hidden_dim: 256
aggregation: sum
project_name: flavor_diffusion
logger_name: null
ckpt_path: null
resume_weight_only: false
do_train: true
do_test: true
do_valid_only: true
input_nodes: /workspace/FlavorGraph/input/nodes_191120.csv
CSP_train: true
